### ISSUE TITLE
iOS-Sample Crash when I click ViewModel

### ISSUE THREAD

**Issue by ChokWah** [dmsurti/AssimpKit#56]
I run iOS Sample in iPad Air2, copy my.obj and my.mtl to app-Document. When I selected the obj in tableview. Then I click view model , it crashed.

Xcode 8.3.2, iPad Air2 - iOS10.3.3 
Myobj file is here. You can unpack and put them in. 
[myObj.zip](https://github.com/dmsurti/AssimpKit/files/1213570/myObj.zip)

![jietu20170810-111138](https://user-images.githubusercontent.com/13447070/29152945-f90a9200-7dbc-11e7-94e3-fe994f3ff970.jpg)

**Comment by dmsurti** [comment]
@ChokWah thanks for reporting this. I have tried with both the Mac and iOS viewers and it does not render, so it is a problem with AssimpKit.

**Comment by dmsurti** [comment]
@ChokWah PR #59 fixes this problem. 

Are you OK with me using the model you have provided as part of AssimpKit test cases? The [AssimpKit licenses](https://github.com/dmsurti/AssimpKit/tree/master/licenses) explicitly mention the usage of such files only for testing purpose. Let me know. Thanks!

**Comment by ChokWah** [comment]
@dmsurti I'm ok with that.


In fact, I'm looking for something like  AssimpKit to solve scenekit load model's problem.How can i load model so beautiful by scenekit just like sketchfab. I don't want to adjust model's effect in xcode everytime.

**Comment by dmsurti** [comment]
>> How can i load model so beautiful by scenekit just like sketchfab. I don't want to adjust model's effect in xcode everytime.

@ChokWah Request you to open issues describing the features you want in AssimpKit that will help you build scenes as per envision and that will be really helpful. Thanks 👍.

**Comment by dmsurti** [comment]
Fixed in #59
