### ISSUE TITLE
iTunes Connect Upload Failed with Error

### ISSUE THREAD

**Issue by magicmikek** [dmsurti/AssimpKit#93]
I added AssimpKit to my Xcode Project. But now I am not able to upload it to iTunes Connect anymore.
These are the errors I am receiving.
<img width="1060" alt="screen shot 2017-12-13 at 23 07 10" src="https://user-images.githubusercontent.com/7288679/33964945-8477385c-e05a-11e7-919e-eaff24f2ff44.png">

**Comment by dmsurti** [comment]
This is not an `AssimpKit` problem but a `carthage` issue which can be fixed by adding a script that removes the `unsupported architectures` based on your project settings.

See this: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/ for the script.

**Comment by magicmikek** [comment]
I did not use Carthage. I manually added the Assimpkit Framework to my Project

**Comment by dmsurti** [comment]
>> I did not use Carthage

Ok, wrong assumption on my part.

>> I manually added the Assimpkit Framework to my Project

Not really recommended that you do so manually. 

Nevertheless, `AssimpKit.framework` contains more architectures than your app and you need to strip out those and the script I referred to should help you strip those out, whether you install with carthage or manually. Hope this helps.

**Comment by magicmikek** [comment]
Do you think I can install Assimpkit with Carthage although I also use cocoa pods?

**Comment by dmsurti** [comment]
Yes, carthage and cocoa pods can be used in same project. PS: Even if you use carthage, you may/will still have to strip out the unsupported architectures.
