### ISSUE TITLE
Carthage Won't Build Assimpkit

### ISSUE THREAD

**Issue by aaronnicholson** [dmsurti/AssimpKit#95]
Hi there!
For some reason, Carthage will pull down Assimpkit into my project but then fails on the build stage. I have verified that 7z is installed add accessible.

Do you know what else I can do? Is there a way to bypass the automatic Build step and get that part done on my own?

TERMINAL OUTPUT:
Aarons-MacBook:ARAppExperimentation aaronnicholson$ carthage update
*** Fetching AssimpKit
*** Checking out AssimpKit at "v1.2.0"
*** xcodebuild output can be found in /var/folders/jz/pnpc67p54ns9vzv8d5092twh0000gn/T/carthage-xcodebuild.wKqsm3.log
*** Building scheme "AssimpKit-iOS" in AssimpKit.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/aaronnicholson/Documents/iOS\ Tutorials/ARAppExperimentation/Carthage/Checkouts/AssimpKit/AssimpKit/AssimpKit.xcworkspace -scheme AssimpKit-iOS -configuration Release -derivedDataPath /Users/aaronnicholson/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/AssimpKit/v1.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jz/pnpc67p54ns9vzv8d5092twh0000gn/T/AssimpKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/aaronnicholson/Documents/iOS Tutorials/ARAppExperimentation/Carthage/Checkouts/AssimpKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jz/pnpc67p54ns9vzv8d5092twh0000gn/T/carthage-xcodebuild.wKqsm3.log

LOG FILE CONTENT:
Attached
[carthage-xcodebuild.wKqsm3.log](https://github.com/dmsurti/AssimpKit/files/1573903/carthage-xcodebuild.wKqsm3.log)

**Comment by dmsurti** [comment]
Your `carthage update` fails because for some unknown reason, your checkout does not have the `.7z` archives. 

From your log:

```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:


Command Line Error:
Cannot find archive
```

which should ideally be:

```
Scanning the drive for archives:
1 file, 13415479 bytes (13 MiB)

Extracting archive: /Users/deepaksurti/tmp/AssimpKitCarthage-iOSDemo-v12/Carthage/Checkouts/AssimpKit/AssimpKit/Library/../Assimp/lib/ios/libassimp-fat.7z
--
Path = /Users/deepaksurti/tmp/AssimpKitCarthage-iOSDemo-v12/Carthage/Checkouts/AssimpKit/AssimpKit/Library/../Assimp/lib/ios/libassimp-fat.7z
Type = 7z
Physical Size = 13415479
Headers Size = 138
Method = LZMA:25
Solid = -
Blocks = 1

Everything is Ok

Size:       122698872
Compressed: 13415479
Extracting iOS fat lib...
```

You need to fix carthage issues. I tried on a sample project with `1.2.0` and there were no issues with carthage installation. There is also a sample project for quick testing of AssimpKit installation with Carthage: https://github.com/dmsurti/AssimpKitCarthage-iOSDemo.

**Comment by anton-plebanovich** [comment]
This one was because paths in build script are not quoted.

**Comment by anton-plebanovich** [comment]
PR with fix - https://github.com/dmsurti/AssimpKit/pull/100

**Comment by dmsurti** [comment]
@anton-plebanovich Thanks so much. I will review this over the weekend/merge it. Cheers.
